#+ summary: hisclass over time for OPs
#+ note: red exclamation mark can be ignored; query works
#+ tags:
#+      - HSN
#+      - HISCLASS
#+      - Occupational mobility

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hsndim: <https://iisg.amsterdam/hsn/dimension/>
PREFIX hsn: <https://iisg.amsterdam/hsn/>
PREFIX hsn-hisco: <https://iisg.amsterdam/hsn2013a/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
prefix relacode: <https://iisg.amsterdam/hsn/code/RELACODE/>
prefix hsnvocab: <https://iisg.amsterdam/hsn2013a/vocab/>


SELECT DISTINCT ?idnr ?person ?occlab ?gebjaar ?hisclass ?ingjaar 
	bif:datediff('year', xsd:gYear(str(?gebjaar)),xsd:gYear(str(?ingjaar))) AS ?age 

WHERE{
  
    ?person hsndim:individualObservation ?obs .
    ?person hsndim:individualObservation/hsndim:GEBJAR ?gebjaar .
    ?person a hsn:OP .
 
    ?obs hsndim:occstring_lc ?occlab .
    ?obs hsndim:IDNR ?idnr .
    ?obs hsndim:PERSNR ?persnr .
    ?obs hsndim:INGJAR ?ingjaar .
    ?obs hsndim:occupationalTitle ?occ2 .
    ?occ2 hsn-hisco:hisclass ?hisclass .
    
}
ORDER BY ?person
