#+ summary: occupational status by religion over time
#+ tags:
#+      - HSN
#+      - religion
#+      - occupation
#+      - hisco
#+      - hisclass
#+      - hiscam

# NB: large number of objects seems required to filter out  duplicate matches 

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hsndim: <https://iisg.amsterdam/hsn/dimension/>
PREFIX hsn: <https://iisg.amsterdam/hsn/>
PREFIX hsn-hisco: <https://iisg.amsterdam/hsn2013a/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
prefix dynatype: <https://iisg.amsterdam/hsn/code/DYNATYPE/>
prefix hsnvocab: <https://iisg.amsterdam/hsn2013a/vocab/>


SELECT DISTINCT  ?indiv ?occobs ?relobs ?occup ?hisclass ?hiscam ?occyear ?relyear ?religie ?occno ?relno 

WHERE {
    ?indiv hsndim:individualObservation ?occobs .
    ?occobs hsndim:occupationalTitle ?occup .
    ?occobs hsndim:INGJAR ?occyear .
    ?occobs hsndim:UIGDAT ?occyear_out .
    ?occobs hsndim:INGVLGNR ?occno .

    ?occup hsn-hisco:hisclass ?hisclass  .
    ?hisco skos:member ?occup .
    ?hisco <https://iisg.amsterdam/hiscam/v131/nl> ?hiscam .

    ?indiv hsndim:individualObservation ?relobs .
    ?relobs hsndim:Kerkgenootschap ?religie .
    ?relobs hsndim:INGJAR ?relyear .
    ?relobs hsndim:INGVLGNR ?relno .

    FILTER(?relno = ?occno)
  
}
