#+ summary: hisclass over time for OPs with place of residence
#+ tags:
#+      - HSN

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hsndim: <https://iisg.amsterdam/hsn/dimension/>
PREFIX hsn: <https://iisg.amsterdam/hsn/>
PREFIX hsn-hisco: <https://iisg.amsterdam/hsn2013a/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
prefix relacode: <https://iisg.amsterdam/hsn/code/RELACODE/>
prefix hsnvocab: <https://iisg.amsterdam/hsn2013a/vocab/>


SELECT ?hisclass ?occvlgnr ?occdat ?gemeente ?adres_ingdat ?adres_utgdat ?subj ?idnr ?sexop

WHERE {
    ?subj hsndim:occstring_lc ?occlab .
    ?subj hsndim:occupationalTitle ?occ2 .
    ?occ2 hsn-hisco:hisclass ?hisclass  .

    ?subj hsndim:INGVLGNR ?occvlgnr .
    ?subj hsndim:INGDAT ?occdat .
    ?subj hsndim:IDNR ?idnr .
    ?subj hsndim:HUISHNR ?huishnr .
    ?subj hsndim:DYNATYPE <https://iisg.amsterdam/hsn/code/DYNATYPE/5> .
    ?subj hsndim:HSNperson ?hsnperson .

    ?opentry hsndim:HSNperson ?hsnperson.
    ?opentry hsndim:SEX_OP ?sexop .

   ?adresobs hsndim:IDNR ?idnr.
   ?adresobs hsndim:HUISHNR ?huishnr .
   ?adresobs hsndim:GEMEENTE ?gemeente . 
   ?adresobs hsndim:ADRESDAT ?adres_ingdat .
   ?adresobs hsndim:ADUITDAT ?adres_utgdat .
   FILTER(?occdat <= ?adres_utgdat && ?occdat >= ?adres_ingdat )
  
  
}
ORDER BY ?idnr
